### ISSUE TITLE
Bug: Object_string对象没有转为json字符串

### ISSUE THREAD

**Issue by EXCALIBURYaoGod** [coze-dev/coze-js#36]
## Steps To Reproduce

1.在js调用Coze-js并创建client，然后创建流式对话，填写相关参数，在additional_messages一项中的content定义如下：
`                additional_messages = [{
                    role: 'user',
                    content: [
                        { type: 'file', file_id: this.fileID },
                        { type: 'text', text: message },
                    ],
                    content_type: 'object_string',
                }];`
其中，this.fileID和message是我脚本预先定义好的string字符串。
2.如果如此定义，Coze服务器会返回一个4000错误码：请求参数错误
3.查阅相关源码后，我发现coze源码是如此定义object_string类型的cotent的
`export type ObjectStringItem =
  | { type: 'text'; text: string }
  | { type: 'file'; file_id: string }
  | { type: 'file'; file_url: string }
  | { type: 'image'; file_id: string }
  | { type: 'image'; file_url: string };`
这里只是定义了content的js对象，而并没有将其转为json string，因此我在自己代码中将content改为了
`content: JSON.stringify([
                        { type: 'file', file_id: this.fileID },
                        { type: 'text', text: message },
                    ]),`
成功发送了正确的请求，获取到了coze的正确响应。
或许你们可以在源码中自动将ObjectStringItem对象转为json字符串，以避免用户手动转类型
-----

Link to code example:

**Comment by jackshen310** [comment]
Thank you for raising this issue and providing such a valuable suggestion!
